import type { MethodologyDetails } from '../../services/dashboard/dashboardService';

const EMPTY: MethodologyDetails = { status: 'unavailable', timeframeStart: null, timeframeEnd: null, collectedSignalCount: 0, eligibleSignalCount: 0, excludedSignalCount: 0, exclusions: {}, sourceCoverage: [], inputFingerprint: null, preprocessingVersion: null, configurationVersion: null, warnings: [] };

export default function MethodologyPanel({ data = EMPTY }: { data?: MethodologyDetails }) {
  return <section className="rounded-xl border border-app-line bg-app-surface p-5 text-slate-200"><h3 className="text-lg font-semibold">Data quality & methodology</h3><p className="mb-4 text-xs text-slate-400">Coverage, filtering and reproducibility details for this stored run.</p>{data.status === 'unavailable' ? <p className="text-sm text-slate-500">Methodology details are unavailable for this legacy result.</p> : <><dl className="grid gap-3 text-sm sm:grid-cols-3"><Metric label="Useful signals" value={`${data.eligibleSignalCount}/${data.collectedSignalCount}`} /><Metric label="Excluded" value={String(data.excludedSignalCount)} /><Metric label="Timeframe" value={data.timeframeStart && data.timeframeEnd ? `${new Date(data.timeframeStart).toLocaleDateString()} – ${new Date(data.timeframeEnd).toLocaleDateString()}` : 'Unavailable'} /></dl><div className="mt-4 grid gap-4 lg:grid-cols-2"><div><h4 className="text-sm font-semibold">Collector coverage</h4><ul className="mt-2 space-y-1 text-sm text-slate-400">{data.sourceCoverage.map(row => <li key={row.collector}>{row.collector}: <span className={row.status === 'completed' ? 'text-emerald-300' : 'text-amber-300'}>{row.status}</span> · {row.eligibleCount} usable</li>)}</ul></div><div><h4 className="text-sm font-semibold">Versions & exclusions</h4><p className="mt-2 break-all text-xs text-slate-400">Preprocessing: {data.preprocessingVersion ?? 'Unavailable'} · Config: {data.configurationVersion ?? 'Unavailable'}<br/>Fingerprint: {data.inputFingerprint ?? 'Unavailable'}<br/>Exclusions: {Object.entries(data.exclusions).map(([reason, count]) => `${reason} (${count})`).join(', ') || 'None'}</p></div></div>{data.warnings.map(warning => <p key={warning} className="mt-3 text-xs text-amber-300">{warning}</p>)}</>}</section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-app-surface-strong p-3"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
