"""initial schema (23 entities)

Revision ID: 7a4040f03592
Revises:
Create Date: 2026-06-07 22:05:42.646807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a4040f03592'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_profiles',
    sa.Column('brand_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('positioning_notes', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('brand_id', name=op.f('pk_brand_profiles'))
    )
    op.create_table('collaboration_candidates',
    sa.Column('candidate_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id', name=op.f('pk_collaboration_candidates'))
    )
    op.create_table('data_sources',
    sa.Column('source_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('source_category', sa.String(length=50), nullable=True),
    sa.Column('access_method', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('rate_limit_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_data_sources'))
    )
    op.create_table('model_versions',
    sa.Column('version_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_identifier', sa.String(length=100), nullable=False),
    sa.Column('prompt_template_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_model_versions'))
    )
    op.create_table('evaluation_runs',
    sa.Column('eval_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('dataset_size', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('f1_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('human_agreement_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['model_versions.version_id'], name=op.f('fk_evaluation_runs_version_id_model_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('eval_id', name=op.f('pk_evaluation_runs'))
    )
    op.create_index(op.f('ix_evaluation_runs_version_id'), 'evaluation_runs', ['version_id'], unique=False)
    op.create_table('previous_collabs',
    sa.Column('collab_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('partner_name', sa.String(length=255), nullable=False),
    sa.Column('outcome_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('collab_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.brand_id'], name=op.f('fk_previous_collabs_brand_id_brand_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collab_id', name=op.f('pk_previous_collabs'))
    )
    op.create_index(op.f('ix_previous_collabs_brand_id'), 'previous_collabs', ['brand_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('run_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target_brand_id', sa.UUID(), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('timeframe_start', sa.Date(), nullable=True),
    sa.Column('timeframe_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('filter_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name=op.f('ck_research_runs_research_runs_status_check')),
    sa.ForeignKeyConstraint(['target_brand_id'], ['brand_profiles.brand_id'], name=op.f('fk_research_runs_target_brand_id_brand_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_research_runs'))
    )
    op.create_index(op.f('ix_research_runs_target_brand_id'), 'research_runs', ['target_brand_id'], unique=False)
    op.create_table('source_configs',
    sa.Column('config_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.String(), nullable=True),
    sa.Column('scope_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name=op.f('fk_source_configs_source_id_data_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_id', name=op.f('pk_source_configs'))
    )
    op.create_index(op.f('ix_source_configs_source_id'), 'source_configs', ['source_id'], unique=False)
    op.create_table('anomaly_events',
    sa.Column('anomaly_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_type', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('observed_value', sa.Numeric(), nullable=False),
    sa.Column('baseline_value', sa.Numeric(), nullable=False),
    sa.Column('deviation_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('probable_cause', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], name=op.f('fk_anomaly_events_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anomaly_id', name=op.f('pk_anomaly_events'))
    )
    op.create_index(op.f('ix_anomaly_events_run_id'), 'anomaly_events', ['run_id'], unique=False)
    op.create_table('extracted_themes',
    sa.Column('theme_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('theme_label', sa.String(length=255), nullable=False),
    sa.Column('theme_category', sa.String(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('growth_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('prevalence_rank', sa.Integer(), nullable=True),
    sa.Column('representative_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], name=op.f('fk_extracted_themes_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('theme_id', name=op.f('pk_extracted_themes'))
    )
    op.create_index(op.f('ix_extracted_themes_run_id'), 'extracted_themes', ['run_id'], unique=False)
    op.create_table('filter_summaries',
    sa.Column('summary_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('total_checked_count', sa.Integer(), nullable=False),
    sa.Column('retained_count', sa.Integer(), nullable=False),
    sa.Column('spam_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('bot_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('duplicate_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('low_quality_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('exclusion_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], name=op.f('fk_filter_summaries_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id', name=op.f('pk_filter_summaries'))
    )
    op.create_index(op.f('ix_filter_summaries_run_id'), 'filter_summaries', ['run_id'], unique=False)
    op.create_table('generated_reports',
    sa.Column('report_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], name=op.f('fk_generated_reports_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', name=op.f('pk_generated_reports'))
    )
    op.create_index(op.f('ix_generated_reports_run_id'), 'generated_reports', ['run_id'], unique=False)
    op.create_table('geo_insights',
    sa.Column('geo_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('sentiment_score_avg', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sentiment_vs_global', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('trend_velocity', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('top_themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location_confidence', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], name=op.f('fk_geo_insights_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('geo_id', name=op.f('pk_geo_insights'))
    )
    op.create_index(op.f('ix_geo_insights_run_id'), 'geo_insights', ['run_id'], unique=False)
    op.create_table('module_runs',
    sa.Column('module_run_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('module_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name=op.f('ck_module_runs_module_runs_status_check')),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], name=op.f('fk_module_runs_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('module_run_id', name=op.f('pk_module_runs'))
    )
    op.create_index(op.f('ix_module_runs_run_id'), 'module_runs', ['run_id'], unique=False)
    op.create_table('run_candidate_selections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('intended_purpose', sa.Text(), nullable=True),
    sa.Column('metric_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['collaboration_candidates.candidate_id'], name=op.f('fk_run_candidate_selections_candidate_id_collaboration_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], name=op.f('fk_run_candidate_selections_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_candidate_selections'))
    )
    op.create_index(op.f('ix_run_candidate_selections_candidate_id'), 'run_candidate_selections', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_run_candidate_selections_run_id'), 'run_candidate_selections', ['run_id'], unique=False)
    op.create_table('run_sentiment_aggregates',
    sa.Column('aggregate_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('weighted_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('positive_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('neutral_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('negative_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('top_aspects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], name=op.f('fk_run_sentiment_aggregates_run_id_research_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name=op.f('fk_run_sentiment_aggregates_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('aggregate_id', name=op.f('pk_run_sentiment_aggregates'))
    )
    op.create_index(op.f('ix_run_sentiment_aggregates_run_id'), 'run_sentiment_aggregates', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_sentiment_aggregates_source_id'), 'run_sentiment_aggregates', ['source_id'], unique=False)
    op.create_table('synthesis_outputs',
    sa.Column('synthesis_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('output_type', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], name=op.f('fk_synthesis_outputs_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('synthesis_id', name=op.f('pk_synthesis_outputs'))
    )
    op.create_index(op.f('ix_synthesis_outputs_run_id'), 'synthesis_outputs', ['run_id'], unique=False)
    op.create_table('candidate_evaluations',
    sa.Column('evaluation_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('selection_id', sa.UUID(), nullable=False),
    sa.Column('collaboration_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('audience_overlap', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('value_alignment', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('risk_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['selection_id'], ['run_candidate_selections.id'], name=op.f('fk_candidate_evaluations_selection_id_run_candidate_selections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evaluation_id', name=op.f('pk_candidate_evaluations'))
    )
    op.create_index(op.f('ix_candidate_evaluations_selection_id'), 'candidate_evaluations', ['selection_id'], unique=False)
    op.create_table('collected_signals',
    sa.Column('signal_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('module_run_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('external_item_id', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('location_mode', sa.String(), nullable=True),
    sa.Column('platform_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spam_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('raw_text IS NOT NULL OR cleaned_text IS NOT NULL', name=op.f('ck_collected_signals_collected_signals_content_present_check')),
    sa.ForeignKeyConstraint(['module_run_id'], ['module_runs.module_run_id'], name=op.f('fk_collected_signals_module_run_id_module_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], name=op.f('fk_collected_signals_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('signal_id', name=op.f('pk_collected_signals')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_collected_signals_content_hash'))
    )
    op.create_index(op.f('ix_collected_signals_module_run_id'), 'collected_signals', ['module_run_id'], unique=False)
    op.create_index(op.f('ix_collected_signals_source_id'), 'collected_signals', ['source_id'], unique=False)
    op.create_table('aspect_sentiments',
    sa.Column('aspect_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('aspect_name', sa.String(length=100), nullable=False),
    sa.Column('sentiment_label', sa.String(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('extraction_method', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], name=op.f('fk_aspect_sentiments_run_id_research_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['collected_signals.signal_id'], name=op.f('fk_aspect_sentiments_signal_id_collected_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('aspect_id', name=op.f('pk_aspect_sentiments'))
    )
    op.create_index(op.f('ix_aspect_sentiments_run_id'), 'aspect_sentiments', ['run_id'], unique=False)
    op.create_index(op.f('ix_aspect_sentiments_signal_id'), 'aspect_sentiments', ['signal_id'], unique=False)
    op.create_table('filter_audits',
    sa.Column('audit_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('source_from_id', sa.UUID(), nullable=True),
    sa.Column('retained_flag', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['collected_signals.signal_id'], name=op.f('fk_filter_audits_signal_id_collected_signals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_from_id'], ['data_sources.source_id'], name=op.f('fk_filter_audits_source_from_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_filter_audits'))
    )
    op.create_index(op.f('ix_filter_audits_signal_id'), 'filter_audits', ['signal_id'], unique=False)
    op.create_index(op.f('ix_filter_audits_source_from_id'), 'filter_audits', ['source_from_id'], unique=False)
    op.create_table('sentiment_results',
    sa.Column('sentiment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('layer_source', sa.String(), nullable=False),
    sa.Column('sentiment_label', sa.String(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['research_runs.run_id'], name=op.f('fk_sentiment_results_run_id_research_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['collected_signals.signal_id'], name=op.f('fk_sentiment_results_signal_id_collected_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sentiment_id', name=op.f('pk_sentiment_results'))
    )
    op.create_index(op.f('ix_sentiment_results_run_id'), 'sentiment_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_sentiment_results_signal_id'), 'sentiment_results', ['signal_id'], unique=False)
    op.create_table('signal_metrics',
    sa.Column('metric_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Numeric(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['collected_signals.signal_id'], name=op.f('fk_signal_metrics_signal_id_collected_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_id', name=op.f('pk_signal_metrics'))
    )
    op.create_index(op.f('ix_signal_metrics_signal_id'), 'signal_metrics', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_metrics_signal_id'), table_name='signal_metrics')
    op.drop_table('signal_metrics')
    op.drop_index(op.f('ix_sentiment_results_signal_id'), table_name='sentiment_results')
    op.drop_index(op.f('ix_sentiment_results_run_id'), table_name='sentiment_results')
    op.drop_table('sentiment_results')
    op.drop_index(op.f('ix_filter_audits_source_from_id'), table_name='filter_audits')
    op.drop_index(op.f('ix_filter_audits_signal_id'), table_name='filter_audits')
    op.drop_table('filter_audits')
    op.drop_index(op.f('ix_aspect_sentiments_signal_id'), table_name='aspect_sentiments')
    op.drop_index(op.f('ix_aspect_sentiments_run_id'), table_name='aspect_sentiments')
    op.drop_table('aspect_sentiments')
    op.drop_index(op.f('ix_collected_signals_source_id'), table_name='collected_signals')
    op.drop_index(op.f('ix_collected_signals_module_run_id'), table_name='collected_signals')
    op.drop_table('collected_signals')
    op.drop_index(op.f('ix_candidate_evaluations_selection_id'), table_name='candidate_evaluations')
    op.drop_table('candidate_evaluations')
    op.drop_index(op.f('ix_synthesis_outputs_run_id'), table_name='synthesis_outputs')
    op.drop_table('synthesis_outputs')
    op.drop_index(op.f('ix_run_sentiment_aggregates_source_id'), table_name='run_sentiment_aggregates')
    op.drop_index(op.f('ix_run_sentiment_aggregates_run_id'), table_name='run_sentiment_aggregates')
    op.drop_table('run_sentiment_aggregates')
    op.drop_index(op.f('ix_run_candidate_selections_run_id'), table_name='run_candidate_selections')
    op.drop_index(op.f('ix_run_candidate_selections_candidate_id'), table_name='run_candidate_selections')
    op.drop_table('run_candidate_selections')
    op.drop_index(op.f('ix_module_runs_run_id'), table_name='module_runs')
    op.drop_table('module_runs')
    op.drop_index(op.f('ix_geo_insights_run_id'), table_name='geo_insights')
    op.drop_table('geo_insights')
    op.drop_index(op.f('ix_generated_reports_run_id'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_filter_summaries_run_id'), table_name='filter_summaries')
    op.drop_table('filter_summaries')
    op.drop_index(op.f('ix_extracted_themes_run_id'), table_name='extracted_themes')
    op.drop_table('extracted_themes')
    op.drop_index(op.f('ix_anomaly_events_run_id'), table_name='anomaly_events')
    op.drop_table('anomaly_events')
    op.drop_index(op.f('ix_source_configs_source_id'), table_name='source_configs')
    op.drop_table('source_configs')
    op.drop_index(op.f('ix_research_runs_target_brand_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_previous_collabs_brand_id'), table_name='previous_collabs')
    op.drop_table('previous_collabs')
    op.drop_index(op.f('ix_evaluation_runs_version_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_table('model_versions')
    op.drop_table('data_sources')
    op.drop_table('collaboration_candidates')
    op.drop_table('brand_profiles')
    # ### end Alembic commands ###
